=== SPGoding/CommandReference/schema.json
{
    "$schema": "http://json-schema.org/schema#",
    "id":"https://raw.githubusercontent.com/pca006132/CommandReference/master/schema.json",
    "type": "object",
    "title": "Root tag",
    "additionalProperties": false,
    "properties": {
        "common-words": {
            "type": "array",
            "items": {
                "type": "array",
                "items": [
                    {
                        "type": "string",
                        "title": "词",
                        "description": "那常用词以及其缩写"
                    },
                    {
                        "type": "string",
                        "title": "描述"
                    }
                ]
            }
        },
        "threads": {
            "type": "object",
            "additionalProperties": false,
            "patternProperties": {
                "https?:\\/\\/(www\\.)?[-a-zA-Z0-9@:%._\\+~#=]{2,256}\\.[a-z]{2,6}\\b([-a-zA-Z0-9@:%_\\+.~#?&//=]*)": {
                    "type": "object",
                    "additionalProperties": false,
                    "properties": {
                        "title": {
                            "type": "string",
                            "title": "帖子标题"
                        },
                        "last-update": {
                            "type": "string",
                            "format": "^\\d{4}-\\d{2}-\\d{2}$"
                        },
                        "tags": {
                            "type": "array",
                            "items": {
                                "type": "string",
                                "enum": [
                                    "基础",
                                    "进阶",
                                    "计算",
                                    "几何",
                                    "算法",
                                    "特技",
                                    "NBT",
                                    "游戏机制",
                                    "黑科技",
                                    "人生经验",
                                    "游戏系统",
                                    "命令介绍",
                                    "原版模组",
                                    "地图作品",
                                    "概念验证",
                                    "OOC生成",
                                    "自定义生成器",
                                    "其他生成器/资源",
                                    "实例",
                                    "过时",
                                    "即将过时",
                                    "英语"
                                ]
                            },
                            "minItems": 1,
                            "maxItems": 5
                        },
                        "category": {
                            "type": "string",
                            "enum": [
                                "有趣问答",
                                "算法逻辑",
                                "系统制作技巧",
                                "NBT介绍",
                                "作品例子",
                                "游戏机制",
                                "教程索引",
                                "命令/格式教程",
                                "常用网站",
                                "生成器/资源",
                                "其他"
                            ]
                        },
                        "version-min": {
                            "type": "integer",
                            "minimum": 8,
                            "maximum": 13
                        },
                        "version-max": {
                            "type": "integer",
                            "minimum": 8,
                            "maximum": 13
                        },
                        "recommended": {
                            "type": "integer",
                            "minimum": 0,
                            "maximum": 2
                        }
                    },
                    "required": [
                        "title", "last-update", "tags", "category", "version-min", "version-max", "recommended"
                    ]
                }
            }
        },
        "tags": {
            "type": "array",
            "items": {
                "type": "string"
            }
        },
        "version": {
            "type": "object",
            "properties": {
                "min": {
                    "type": "integer"
                },
                "max": {
                    "type": "integer"
                }
            },
            "required": [
                "min", "max"
            ],
            "additionalProperties": false
        }
    },
    "required": [
        "common-words", "threads", "tags", "version"
    ]
}

=== SPGoding/CommandReference/data.json
{
    "common-words": [
        ["AEC", "AreaEffectCloud, 药水云"],
        ["AS, 盔甲架, 装备架", "ArmorStand"],
        ["cb、命令方块、指令方块", "command block"],
        ["ccb", "chain command block, 链锁命令方块"],
        ["exe", "execute"],
        ["gm", "gamemode"],
        ["icb", "impulse command block, 就是普通的命令方块(脉冲命令方块)"],
        ["lt", "loot table, 可掠夺物品表(用以修改生物掉落)"],
        ["OOC", "\"一条\"命令(Only One Command)。即把多条命令压缩为一条summon命令, 或以一条summon命令生成多个命令方块"],
        ["rcb", "repeating command block, 循环命令方块"],
        ["spcl", "spreadplayers指令做的chunk loader(区块加载器)，注这简写极少用"],
        ["stats", "stats指令"],
        ["stat", "玩家统计(记分板)"],
        ["判据、准则", "scoreboard的criteria(wiki官方译名:准则)"],
        ["命令、指令、\"代码\"", "command"],
        ["数据值、伤害值", "damage"],
        ["显示区、显示位置", "display slot(wiki官方译名:显示位置)"],
        ["目标、对象、变数", "scoreboard的objective(wiki官方译名:目标)"],
        ["目标选择器、实体选择器", "target selector"],
        ["碰撞箱", "hitbox"],
        ["触发器", "trigger"],
        ["计分板、记分板、scb", "scoreboard(wiki官方译名:记分板)"],
        ["文本JSON", "Raw JSON(/tellraw, /title等)"]
    ],
    "tags": [
        "基础",
        "进阶",
        "计算",
        "几何",
        "算法",
        "特技",
        "NBT",
        "游戏机制",
        "黑科技",
        "人生经验",
        "游戏系统",
        "命令介绍",
        "原版模组",
        "地图作品",
        "概念验证",
        "OOC生成",
        "自定义生成器",
        "其他生成器/资源",
        "实例",
        "过时",
        "即将过时",
        "英语"
    ],
    "version": {
        "min": 8,
        "max": 13
    },
    "threads": {
        "http://www.mcbbs.net/thread-787422-1-1.html": {
            "title": "NBT操作：从入门到mjsb",
            "last-update": "2018-03-24",
            "tags": ["基础", "命令介绍", "NBT"],
            "category": "命令/格式教程",
            "version-min": 13,
            "version-max": 13,
            "recommended": 2
        },
        "http://www.mcbbs.net/thread-786316-1-1.html": {
            "title": "鱼乐无穷 —— 热带鱼生成器",
            "last-update": "2018-03-09",
            "tags": ["自定义生成器"],
            "category": "生成器/资源",
            "version-min": 13,
            "version-max": 13,
            "recommended": 0
        },
        "http://www.mcbbs.net/thread-785724-1-1.html": {
            "title": "原版“数据生成器”——获取各种ID及命令格式",
            "last-update": "2018-03-10",
            "tags": ["进阶"],
            "category": "其他",
            "version-min": 13,
            "version-max": 13,
            "recommended": 1
        },
        "http://www.mcbbs.net/thread-779319-1-1.html": {
            "title": "石锤！原版自瞄！",
            "last-update": "2018-03-10",
            "tags": ["进阶","实例", "计算"],
            "category": "作品例子",
            "version-min": 13,
            "version-max": 13,
            "recommended": 1
        }
    }
}
